package filter

import (
	"path/filepath"
	"strings"
)

// ─── Default skip lists ───────────────────────────────────────────────────────

// skippedExtensions are file extensions that are never worth reviewing —
// lock files, binaries, assets, and minified bundles.
var skippedExtensions = []string{
	// Dependency lock / manifest files
	".lock", ".sum",
	// Images
	".png", ".jpg", ".jpeg", ".gif", ".webp", ".bmp", ".tiff",
	// Vector / font / icon assets
	".svg", ".ico", ".woff", ".woff2", ".ttf", ".eot",
	// Documents / archives
	".pdf", ".zip", ".tar", ".gz", ".bz2", ".xz", ".7z",
	// Compiled / minified
	".min.js", ".min.css",
	// Compiled binaries / objects
	".exe", ".dll", ".so", ".dylib", ".o", ".a",
	// Notebook / data formats (large, not reviewable as diffs)
	".ipynb", ".parquet", ".csv", ".tsv",
	// Certificates / keys (should never be in source, but skip if they are)
	".pem", ".p12", ".pfx", ".crt", ".cer", ".key",
}

// skippedPaths are directory prefixes we always skip.
var skippedPaths = []string{
	"vendor/",
	"node_modules/",
	"dist/",
	"build/",
	"out/",
	".github/",
	".git/",
	"migrations/",    // SQL schema migrations — mostly DDL, not logic
	"testdata/",
	"mocks/",
	"mock/",
	"__mocks__/",
	"__generated__/",
	"generated/",
	".next/",         // Next.js build output
	".nuxt/",         // Nuxt build output
	"coverage/",      // Test coverage reports
	"public/",        // Static assets directory (common in web projects)
}

// skippedFilenames are exact file names that are always skipped regardless
// of directory.
var skippedFilenames = []string{
	"package-lock.json",
	"yarn.lock",
	"pnpm-lock.yaml",
	"bun.lockb",
	"go.sum",
	"Cargo.lock",
	"poetry.lock",
	"Pipfile.lock",
	"composer.lock",
	"Gemfile.lock",
	"mix.lock",
	"flake.lock",    // Nix flake lock
	".DS_Store",
	"Thumbs.db",
}

// generatedFileHeaders are comment prefixes that indicate auto-generated files.
// We check the first line of the patch for these.
var generatedFileHeaders = []string{
	"// Code generated",
	"// DO NOT EDIT",
	"/* Code generated",
	"# Code generated",
	"# DO NOT EDIT",
	"// This file is auto-generated",
	"/* This file is auto-generated",
	"// AUTO-GENERATED",
	"/* AUTO-GENERATED",
	"// Generated by",
	"# Generated by",
}

// ─── Public API ───────────────────────────────────────────────────────────────

// ShouldSkip returns true when a file should not be sent to the AI reviewer.
// It checks, in order:
//  1. Exact filename match (go.sum, yarn.lock, etc.)
//  2. File extension (images, archives, binaries, etc.)
//  3. Path prefix (vendor/, node_modules/, etc.)
//  4. Auto-generated file detection (first line of patch)
//  5. Custom ignore patterns from .ai-reviewer.yml
func ShouldSkip(filename, patch string, repoConfig *RepoConfig) bool {
	base := filepath.Base(filename)

	// 1. Exact filename
	for _, name := range skippedFilenames {
		if base == name {
			return true
		}
	}

	// 2. Extension — check the full filename because ".min.js" is two extensions
	lowerFilename := strings.ToLower(filename)
	for _, ext := range skippedExtensions {
		if strings.HasSuffix(lowerFilename, ext) {
			return true
		}
	}

	// 3. Path prefix
	for _, prefix := range skippedPaths {
		if strings.HasPrefix(filename, prefix) {
			return true
		}
	}

	// 4. Auto-generated file detection — inspect the first added line of the patch
	if isGeneratedFile(patch) {
		return true
	}

	// 5. Repo-level custom ignore patterns from .ai-reviewer.yml
	if repoConfig != nil {
		for _, pattern := range repoConfig.IgnorePaths {
			// Try matching against the full path
			if matched, _ := filepath.Match(pattern, filename); matched {
				return true
			}
			// Also try matching against the base name for simple patterns
			if matched, _ := filepath.Match(pattern, base); matched {
				return true
			}
		}
	}

	return false
}

// isGeneratedFile checks whether the patch begins with a well-known
// auto-generated file header. The patch starts with `+` for each added line,
// so we strip the leading `+` when checking.
func isGeneratedFile(patch string) bool {
	if patch == "" {
		return false
	}

	// Look at the first non-hunk, non-context line in the patch.
	for _, line := range strings.SplitN(patch, "\n", 20) {
		// Skip hunk headers and context lines — look for first content line.
		if strings.HasPrefix(line, "@@") || strings.HasPrefix(line, " ") || strings.HasPrefix(line, "-") {
			continue
		}
		if strings.HasPrefix(line, "+") {
			content := strings.TrimSpace(line[1:])
			for _, header := range generatedFileHeaders {
				if strings.HasPrefix(content, header) {
					return true
				}
			}
			// Found the first real content line but it's not a generated header.
			return false
		}
	}
	return false
}

// ApplyMaxFiles truncates files to at most maxFiles, logging how many were
// dropped. Returns the files to review and a flag indicating truncation.
func ApplyMaxFiles(files []string, maxFiles int) ([]string, bool) {
	if len(files) <= maxFiles {
		return files, false
	}
	return files[:maxFiles], true
}

// FilterFiles applies ShouldSkip to a slice of (filename, patch) pairs and
// returns only the ones that should be reviewed.
type FileEntry struct {
	Filename string
	Patch    string
}

func FilterFiles(files []FileEntry, repoConfig *RepoConfig) []FileEntry {
	result := make([]FileEntry, 0, len(files))
	for _, f := range files {
		if !ShouldSkip(f.Filename, f.Patch, repoConfig) {
			result = append(result, f)
		}
	}
	return result
}
