package filter

import (
	"testing"
)

func TestShouldSkip_LockFiles(t *testing.T) {
	cases := []string{
		"go.sum",
		"package-lock.json",
		"yarn.lock",
		"pnpm-lock.yaml",
		"Cargo.lock",
		"poetry.lock",
		"Gemfile.lock",
	}
	for _, name := range cases {
		if !ShouldSkip(name, "", nil) {
			t.Errorf("expected %q to be skipped", name)
		}
	}
}

func TestShouldSkip_BinaryExtensions(t *testing.T) {
	cases := []string{
		"logo.png",
		"photo.jpg",
		"icon.ico",
		"font.woff2",
		"archive.zip",
		"bundle.min.js",
		"styles.min.css",
		"binary.exe",
	}
	for _, name := range cases {
		if !ShouldSkip(name, "", nil) {
			t.Errorf("expected %q to be skipped", name)
		}
	}
}

func TestShouldSkip_SkippedPaths(t *testing.T) {
	cases := []string{
		"vendor/github.com/foo/bar/file.go",
		"node_modules/react/index.js",
		"dist/bundle.js",
		"build/output.js",
		".github/workflows/ci.yml",
		"testdata/fixtures/input.json",
		"mocks/generated_mock.go",
		"__generated__/types.ts",
	}
	for _, path := range cases {
		if !ShouldSkip(path, "", nil) {
			t.Errorf("expected %q to be skipped", path)
		}
	}
}

func TestShouldSkip_ReviewableFiles(t *testing.T) {
	cases := []string{
		"main.go",
		"internal/server/handler.go",
		"src/components/Button.tsx",
		"api/routes.py",
		"lib/auth/jwt.js",
		"README.md",     // Markdown is worth reviewing (logic changes in docs)
		"Dockerfile",
	}
	for _, name := range cases {
		if ShouldSkip(name, "", nil) {
			t.Errorf("expected %q to NOT be skipped", name)
		}
	}
}

func TestShouldSkip_GeneratedFile(t *testing.T) {
	generatedPatch := `@@ -0,0 +1,5 @@
+// Code generated by protoc-gen-go. DO NOT EDIT.
+package pb
+
+type Foo struct{}
`
	if !ShouldSkip("pb/foo.pb.go", generatedPatch, nil) {
		t.Error("expected generated file to be skipped")
	}
}

func TestShouldSkip_NotGeneratedFile(t *testing.T) {
	normalPatch := `@@ -1,3 +1,4 @@
 package main
+
+import "fmt"
 `
	if ShouldSkip("main.go", normalPatch, nil) {
		t.Error("expected normal file to NOT be skipped")
	}
}

func TestShouldSkip_CustomIgnorePatterns(t *testing.T) {
	cfg := &RepoConfig{
		IgnorePaths: []string{
			"scripts/**",
			"docs/**",
			"**/*.generated.go",
		},
	}

	shouldSkip := []string{
		"scripts/deploy.sh",
		"docs/api.md",
		"internal/foo.generated.go",
	}
	for _, path := range shouldSkip {
		if !ShouldSkip(path, "", cfg) {
			t.Errorf("expected %q to be skipped by custom pattern", path)
		}
	}
}

func TestShouldSkip_CaseInsensitiveExtensions(t *testing.T) {
	cases := []string{
		"image.PNG",
		"photo.JPG",
		"icon.ICO",
	}
	for _, name := range cases {
		if !ShouldSkip(name, "", nil) {
			t.Errorf("expected %q to be skipped (case-insensitive extension check)", name)
		}
	}
}

func TestMeetsSeverityThreshold(t *testing.T) {
	cases := []struct {
		comment string
		min     string
		want    bool
	}{
		{"error", "suggestion", true},
		{"warning", "suggestion", true},
		{"suggestion", "suggestion", true},
		{"error", "warning", true},
		{"warning", "warning", true},
		{"suggestion", "warning", false},
		{"error", "error", true},
		{"warning", "error", false},
		{"suggestion", "error", false},
	}
	for _, tc := range cases {
		got := MeetsSeverityThreshold(tc.comment, tc.min)
		if got != tc.want {
			t.Errorf("MeetsSeverityThreshold(%q, %q) = %v, want %v",
				tc.comment, tc.min, got, tc.want)
		}
	}
}

func TestIsCategoryEnabled(t *testing.T) {
	cfg := &RepoConfig{
		Categories: []string{"bug", "security"},
	}

	if !IsCategoryEnabled("bug", cfg) {
		t.Error("bug should be enabled")
	}
	if !IsCategoryEnabled("security", cfg) {
		t.Error("security should be enabled")
	}
	if IsCategoryEnabled("performance", cfg) {
		t.Error("performance should NOT be enabled")
	}
}

func TestIsCategoryEnabled_EmptyList(t *testing.T) {
	cfg := &RepoConfig{Categories: []string{}}
	// Empty list means all categories are enabled.
	if !IsCategoryEnabled("bug", cfg) {
		t.Error("with empty category list, all categories should be enabled")
	}
	if !IsCategoryEnabled("performance", cfg) {
		t.Error("with empty category list, all categories should be enabled")
	}
}

func TestFilterFiles(t *testing.T) {
	files := []FileEntry{
		{Filename: "main.go", Patch: "+code"},
		{Filename: "go.sum", Patch: "+hash"},
		{Filename: "vendor/lib/lib.go", Patch: "+code"},
		{Filename: "internal/handler.go", Patch: "+code"},
		{Filename: "logo.png", Patch: ""},
	}

	result := FilterFiles(files, nil)

	if len(result) != 2 {
		t.Fatalf("expected 2 reviewable files, got %d", len(result))
	}
	if result[0].Filename != "main.go" {
		t.Errorf("expected main.go, got %s", result[0].Filename)
	}
	if result[1].Filename != "internal/handler.go" {
		t.Errorf("expected internal/handler.go, got %s", result[1].Filename)
	}
}
